// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mitayush/visa-txn/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Create(ctx context.Context, account *model.Account) (*model.Account, error) {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) (*model.Account, error)); ok {
		return returnFunc(ctx, account)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = returnFunc(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = returnFunc(ctx, account)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - account *model.Account
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, account interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, account)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, account *model.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Account
		if args[1] != nil {
			arg1 = args[1].(*model.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(account1 *model.Account, err error) *MockAccountRepository_Create_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(ctx context.Context, account *model.Account) (*model.Account, error)) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByDocumentNumber provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) ExistsByDocumentNumber(ctx context.Context, documentNumber string) (bool, error) {
	ret := _mock.Called(ctx, documentNumber)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByDocumentNumber")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, documentNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, documentNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, documentNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_ExistsByDocumentNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByDocumentNumber'
type MockAccountRepository_ExistsByDocumentNumber_Call struct {
	*mock.Call
}

// ExistsByDocumentNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - documentNumber string
func (_e *MockAccountRepository_Expecter) ExistsByDocumentNumber(ctx interface{}, documentNumber interface{}) *MockAccountRepository_ExistsByDocumentNumber_Call {
	return &MockAccountRepository_ExistsByDocumentNumber_Call{Call: _e.mock.On("ExistsByDocumentNumber", ctx, documentNumber)}
}

func (_c *MockAccountRepository_ExistsByDocumentNumber_Call) Run(run func(ctx context.Context, documentNumber string)) *MockAccountRepository_ExistsByDocumentNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_ExistsByDocumentNumber_Call) Return(b bool, err error) *MockAccountRepository_ExistsByDocumentNumber_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccountRepository_ExistsByDocumentNumber_Call) RunAndReturn(run func(ctx context.Context, documentNumber string) (bool, error)) *MockAccountRepository_ExistsByDocumentNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAccountID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetByAccountID(ctx context.Context, accountID int64) (*model.Account, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountID")
	}

	var r0 *model.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*model.Account, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *model.Account); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountID'
type MockAccountRepository_GetByAccountID_Call struct {
	*mock.Call
}

// GetByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int64
func (_e *MockAccountRepository_Expecter) GetByAccountID(ctx interface{}, accountID interface{}) *MockAccountRepository_GetByAccountID_Call {
	return &MockAccountRepository_GetByAccountID_Call{Call: _e.mock.On("GetByAccountID", ctx, accountID)}
}

func (_c *MockAccountRepository_GetByAccountID_Call) Run(run func(ctx context.Context, accountID int64)) *MockAccountRepository_GetByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetByAccountID_Call) Return(account *model.Account, err error) *MockAccountRepository_GetByAccountID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_GetByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID int64) (*model.Account, error)) *MockAccountRepository_GetByAccountID_Call {
	_c.Call.Return(run)
	return _c
}
