// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mitayush/visa-txn/internal/model"
	"github.com/mitayush/visa-txn/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionAuditRepository creates a new instance of MockTransactionAuditRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionAuditRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionAuditRepository {
	mock := &MockTransactionAuditRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionAuditRepository is an autogenerated mock type for the TransactionAuditRepository type
type MockTransactionAuditRepository struct {
	mock.Mock
}

type MockTransactionAuditRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionAuditRepository) EXPECT() *MockTransactionAuditRepository_Expecter {
	return &MockTransactionAuditRepository_Expecter{mock: &_m.Mock}
}

// InsertTransactionAuditWithConn provides a mock function for the type MockTransactionAuditRepository
func (_mock *MockTransactionAuditRepository) InsertTransactionAuditWithConn(ctx context.Context, conn repository.DBTX, audit *model.TransactionAudit) error {
	ret := _mock.Called(ctx, conn, audit)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransactionAuditWithConn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.DBTX, *model.TransactionAudit) error); ok {
		r0 = returnFunc(ctx, conn, audit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransactionAuditWithConn'
type MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call struct {
	*mock.Call
}

// InsertTransactionAuditWithConn is a helper method to define mock.On call
//   - ctx context.Context
//   - conn repository.DBTX
//   - audit *model.TransactionAudit
func (_e *MockTransactionAuditRepository_Expecter) InsertTransactionAuditWithConn(ctx interface{}, conn interface{}, audit interface{}) *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call {
	return &MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call{Call: _e.mock.On("InsertTransactionAuditWithConn", ctx, conn, audit)}
}

func (_c *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call) Run(run func(ctx context.Context, conn repository.DBTX, audit *model.TransactionAudit)) *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.DBTX
		if args[1] != nil {
			arg1 = args[1].(repository.DBTX)
		}
		var arg2 *model.TransactionAudit
		if args[2] != nil {
			arg2 = args[2].(*model.TransactionAudit)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call) Return(err error) *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call) RunAndReturn(run func(ctx context.Context, conn repository.DBTX, audit *model.TransactionAudit) error) *MockTransactionAuditRepository_InsertTransactionAuditWithConn_Call {
	_c.Call.Return(run)
	return _c
}
