// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mitayush/visa-txn/internal/model"
	"github.com/mitayush/visa-txn/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// GetByIdempotencyKey provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (*model.Transaction, error) {
	ret := _mock.Called(ctx, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *model.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Transaction, error)); ok {
		return returnFunc(ctx, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = returnFunc(ctx, idempotencyKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockTransactionRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - idempotencyKey string
func (_e *MockTransactionRepository_Expecter) GetByIdempotencyKey(ctx interface{}, idempotencyKey interface{}) *MockTransactionRepository_GetByIdempotencyKey_Call {
	return &MockTransactionRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, idempotencyKey)}
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, idempotencyKey string)) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) Return(transaction *model.Transaction, err error) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string) (*model.Transaction, error)) *MockTransactionRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// InsertTransactionWithConn provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) InsertTransactionWithConn(ctx context.Context, conn repository.DBTX, tx *model.Transaction) (*model.Transaction, error) {
	ret := _mock.Called(ctx, conn, tx)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransactionWithConn")
	}

	var r0 *model.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.DBTX, *model.Transaction) (*model.Transaction, error)); ok {
		return returnFunc(ctx, conn, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.DBTX, *model.Transaction) *model.Transaction); ok {
		r0 = returnFunc(ctx, conn, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.DBTX, *model.Transaction) error); ok {
		r1 = returnFunc(ctx, conn, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_InsertTransactionWithConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertTransactionWithConn'
type MockTransactionRepository_InsertTransactionWithConn_Call struct {
	*mock.Call
}

// InsertTransactionWithConn is a helper method to define mock.On call
//   - ctx context.Context
//   - conn repository.DBTX
//   - tx *model.Transaction
func (_e *MockTransactionRepository_Expecter) InsertTransactionWithConn(ctx interface{}, conn interface{}, tx interface{}) *MockTransactionRepository_InsertTransactionWithConn_Call {
	return &MockTransactionRepository_InsertTransactionWithConn_Call{Call: _e.mock.On("InsertTransactionWithConn", ctx, conn, tx)}
}

func (_c *MockTransactionRepository_InsertTransactionWithConn_Call) Run(run func(ctx context.Context, conn repository.DBTX, tx *model.Transaction)) *MockTransactionRepository_InsertTransactionWithConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.DBTX
		if args[1] != nil {
			arg1 = args[1].(repository.DBTX)
		}
		var arg2 *model.Transaction
		if args[2] != nil {
			arg2 = args[2].(*model.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_InsertTransactionWithConn_Call) Return(transaction *model.Transaction, err error) *MockTransactionRepository_InsertTransactionWithConn_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_InsertTransactionWithConn_Call) RunAndReturn(run func(ctx context.Context, conn repository.DBTX, tx *model.Transaction) (*model.Transaction, error)) *MockTransactionRepository_InsertTransactionWithConn_Call {
	_c.Call.Return(run)
	return _c
}
